n1 = int(input(" digite um numero:"))
n2 = int(input(" digite outro numero:"))
print(f' {n1} + {n2} = {n1+n2}')
print(f' {n1} - {n2} = {n1-n2}')
print(f' {n1} * {n2} = {n1*n2}')
print(f' {n1} / {n2} = {n1/n2}')